# Generated by Django 6.0 on 2026-01-05 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biographie')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('is_diaspora', models.BooleanField(default=False, verbose_name="Vit à l'étranger")),
                ('relationship_goal', models.CharField(choices=[('serious', 'Relation Sérieuse'), ('marriage', 'Mariage'), ('friendship', 'Amitié'), ('dating', 'Rencontre légère')], default='serious', max_length=20, verbose_name='Recherche')),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/', verbose_name='Photo')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Photo de couverture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Photo de profil',
                'verbose_name_plural': 'Photos de profil',
                'ordering': ['-is_cover', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='profiles_pr_gender_fc2e15_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city'], name='profiles_pr_city_491350_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_diaspora'], name='profiles_pr_is_dias_9530bc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['relationship_goal'], name='profiles_pr_relatio_4a0017_idx'),
        ),
    ]
