# Generated by Django 6.0 on 2026-01-12 10:14

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[apps.profiles.models.validate_is_adult],
                verbose_name="Date de naissance",
            ),
        ),
    ]
