# Generated by Django 5.2.9 on 2025-12-15 15:24

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/%Y/%m/%d/', verbose_name='Image de couverture')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Contenu de l'article")),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='Méta-description (SEO)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=10, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveSmallIntegerField(default=0, verbose_name='Temps de lecture (min)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.category', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
