# Generated by Django 6.0 on 2026-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Avatar / Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_method',
            field=models.CharField(default='email', editable=False, max_length=20, verbose_name="Méthode d'enregistrement"),
        ),
    ]
